---
# tasks file for rhv_snapshot_report
- name: Gets VMs list
  ovirt.ovirt.ovirt_vm_info:
    auth:
      hostname: "{{ rhv_hostname }}"
      insecure: true
      username: "{{ rhv_user }}"
      password: "{{ rhv_password }}"
    pattern: name=*
    follow:
      - snapshots
  register: vms

- name: Creates report
  ansible.builtin.template:
    src: report.j2
    dest: /tmp/report.csv

- name: Send report through mail
  community.general.mail:
    host: "{{ mail_smtp_host }}"
    port: 25
    subject: "{{ mail_subject }}"
    body: "{{ mail_body }}"
    from: "{{ mail_sender }}"
    to: "{{ mail_recipient }}"
    attach: /tmp/report.csv

- name: Removes report
  ansible.builtin.file:
    path: /tmp/report.csv
    state: absent
